#!/usr/bin/env bash
set -euo pipefail


for post in posts/*.md; do
	creation_date="$(yq --front-matter extract '.date' "$post")"
	touch -t "${creation_date}2137" "$post"
done

mkdir -p build
cp -R assets build
cp ./*.css build
cp rss.xml build
cp public.key build
cp robots.txt build

# Depends on BSD "date" :(

MD_RENDERER='DATE="$(date -j -f "%Y%m%d" $(yq --front-matter extract ".date" "$md_file") "+%A, %d %B %Y")" pandoc --verbose --lua-filter tools/anchor-links.lua --lua-filter tools/append-date.lua -V description:XDXD --template post.html --metadata title:XDD --metadata lang:en'
ssb \
	-m "$MD_RENDERER" \
	-o build \
	-p posts \
	index.md writing.md contact.md
