#!/usr/bin/env bash
set -euo pipefail


for post in posts/*.md; do
	creation_date="$(yq --front-matter extract '.date' "$post")"
	touch -t "${creation_date}2137" "$post"
done

mkdir -p build
cp -R assets build
cp ./*.css build
cp rss.xml build
cp public.key build
cp robots.txt build

# Depends on BSD "date" :(

MD_RENDERER='PUBLISHED_DATE="$(date -j -f "%Y%m%d" $(yq --front-matter extract ".date" "$md_file") "+%A, %d %B %Y")" UPDATED_DATE="$(date -j -f "%Y%m%d" $(yq --front-matter extract ".updated" "$md_file") "+%A, %d %B %Y")" pandoc --title "$(yq --front-matter extract ".title" "$md_file")" -V description="$(yq --front-matter extract ".description" "$md_file")" --lua-filter tools/anchor-links.lua --lua-filter tools/append-date.lua --template post.html --toc'
ssb \
	-m "$MD_RENDERER" \
	-o build \
	-p posts \
	index.md writing.md contact.md
